baseURL: https://wonderer11.github.io/

locale: en

title: Wonderland

theme: hugo-theme-stack-4.0.3

defaultContentLanguage: en
hasCJKLanguage: true
    
pagination:
  pagerSize: 20
  
permalinks:
  post: /p/:slug/
  page: /:slug/

