baseURL: 'https://example.org/'
theme: 'hugo-theme-stack-3.27.0'

pagination:
    pagerSize: 20

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
defaultContentLanguage: en

defaultContentLanguageInSubdir: true

languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    title: 'Wonderland'
    params:
        sidebar:
            subtitle: "A home for wonderer"

  zh-hk:
    languageCode: zh-hk
    languageName: 粵語
    contentDir: content/zh-hk
    title: 發夢站
    params:
        sidebar:
            subtitle: 用愛發夢

  zh-tw:
    languageCode: zh-tw
    languageName: 華語
    contentDir: content/zh-tw
    title: 發夢站
    params:
        sidebar:
            subtitle: 用愛發夢

