en:
  direction: 'ltr'
  contentDir: 'content/en'
  disabled: false
  label: 'English'
  locale: 'en'
  title: 'Wonderland'
  weight: 1
  params:
    sidebar:
      subtitle: "A home for wonderer"
  menus:
    main:
      - identifier: home
        name: Home
        pageRef: /
        params:
          icon: home         
      - identifier: about
        name: About
        pageRef: /about
        params:
          icon: user
      - identifier: archives
        name: Archives
        pageRef: page/archives
        params:
          icon: archives
      - identifier: search
        name: Search
        pageRef: page/search
        params:
          icon: search

zh-hk:
  direction: 'ltr'
  contentDir: 'content/zh-hk'
  disabled: false
  label: '粵語'
  locale: 'zh-hk'
  title: '發夢站'
  weight: 2
  params:
    sidebar:
      subtitle: 用愛發夢
  menus:
    main:
      - identifier: home
        name: 主頁
        pageRef: /
        params:
          icon: home
      - identifier: about
        name: 關於
        pageRef: /about
        params:
          icon: user
      - identifier: archives
        name: 檔案
        pageRef: page/archives
        params:
          icon: archives
      - identifier: search
        name: 搜尋
        pageRef: page/search
        params:
          icon: search

zh-tw:
  direction: 'ltr'
  contentDir: 'content/zh-tw'
  disabled: false
  label: '華語'
  locale: 'zh-tw'
  title: '發夢站'
  weight: 3
  params:
    sidebar:
      subtitle: 用愛發夢
  menus:
    main:
      - identifier: home
        name: 主頁
        pageRef: /
        params:
          icon: home
      - identifier: about
        name: 關於
        pageRef: /about
        params:
          icon: user
      - identifier: archives
        name: 檔案
        pageRef: page/archives
        params:
          icon: archives
      - identifier: search
        name: 搜尋
        pageRef: page/search
        params:
          icon: search
