en:
  direction: 'ltr'
  contentDir: 'content/en'
  disabled: false
  label: 'English'
  locale: 'en'
  title: 'Wonderland'
  weight: 1
  params:
    sidebar:
      subtitle: "A home for wonderer"
  menus:
    main:
      - identifier: home
        name: Home
        url: /
        params:
          icon: home
          
      - identifier: about
        name: About
        url: /about
        params:
          icon: user
          


zh-hk:
  direction: 'ltr'
  contentDir: 'content/zh-hk'
  disabled: false
  label: '粵語'
  locale: 'zh-hk'
  title: '發夢站'
  weight: 2
  params:
    sidebar:
      subtitle: 用愛發夢
  menus:
    main:
      - identifier: home
        name: 主頁
        url: /
        params:
          icon: home


zh-tw:
  direction: 'ltr'
  contentDir: 'content/zh-tw'
  disabled: false
  label: '華語'
  locale: 'zh-tw'
  title: '發夢站'
  weight: 3
  params:
    sidebar:
      subtitle: 用愛發夢
  menus:
    main:
      - identifier: home
        name: 主頁
        url: /
        params:
          icon: home
