en:
  contentDir: content/en
  label: English
  title: "Wonderland"
  weight: 1
  params:
    sidebar:
      subtitle: "A home for wonderer"

zh-hk:
  contentDir: content/zh-hk
  label: 粵語
  title: 發夢站
  weight: 2
  params:
    sidebar:
      subtitle: 用愛發夢
      
zh-tw:
  contentDir: content/zh-tw
  label: 華語
  title: 發夢站
  weight: 3
  params:
    sidebar:
      subtitle: 用愛發夢